In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import mlxtend

print("Everything works!")

Matplotlib is building the font cache; this may take a moment.

Everything works!

In [2]:
calls = pd.read_csv("calls.csv")

calls.head()

   timestamp  caller  callee  duration
0        184     300     301       121
1       3920     512     299       670
2       5623     301     300       504
3       9252     401     457        -1
4      15466     512       0         5

In [3]:
calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  3600 non-null   int64
 1   caller     3600 non-null   int64
 2   callee     3600 non-null   int64
 3   duration   3600 non-null   int64
dtypes: int64(4)
memory usage: 112.6 KB

In [4]:
calls.describe()

          timestamp       caller       callee     duration
count  3.600000e+03  3600.000000  3600.000000  3600.000000
mean   1.281670e+06   349.840833   354.581111    56.790833
std    6.662889e+05   226.328594   221.136143   176.862896
min    1.840000e+02     0.000000     0.000000    -1.000000
25%    7.501832e+05   143.000000   163.750000     0.000000
50%    1.250542e+06   335.000000   354.000000    10.000000
75%    1.819620e+06   560.000000   552.000000    50.000000
max    2.416399e+06   846.000000   845.000000  5138.000000

In [5]:
calls.isna().sum()

timestamp    0
caller       0
callee       0
duration     0
dtype: int64